### ISSUE TITLE
Code License

### ISSUE THREAD

**Issue by WillowMauldin** [christinecha/gridfolio#1]
Awesome looking project, but what's it licensed under? Right now it's under an implicit copyright,  meaning that nobody is really allowed to use it.

**Comment by christinecha** [comment]
Updated! Thanks for the reminder!

Christine Cha

RECENT PROJECTS + NEWS --
Clickbait Generator ranked #2 on Product Hunt
https://www.producthunt.com/tech/clickbait-generator
CircleMatch is now available on the App Store
https://itunes.apple.com/us/app/circlematch-minimalistic-sliding/id1082737491?ls=1&mt=8
